<?php

function turn_ooyala_node_view($node, $view_mode, $langcode){

	$node_content = $node->content['body'][0]['#markup'];
	preg_match_all("|\[video-ooyala:\d+\]|",$node_content,$matches);
	preg_match_all("|\[video-ooyala-player:\d+\]|",$node_content,$matches_player);

	// print '<pre>';
	// var_dump($node_content);
	// print '</pre>';

	$i = 0;
	if(!empty($matches[0])){
		$matches = $matches[0];

		foreach($matches as $match) {
			$match = substr($match, 14,-1);
			$node_match = node_load($match);
			$item = isset($node_match->field_ooyala_video) ? $node_match->field_ooyala_video['und'][0] : NULL;
			$preset = NULL;

			$link_url = url('ooyalavideo/' .$item['value'],
				array(
				  'query'=> array(
					'width' => variable_get('ooyala_colorbox_width', 500),
					'height' => variable_get('ooyala_colorbox_height', 400),
					'KeepThis' => 'true',
					'TB_iframe' => 'true',
				  ),
				  'absolute' => TRUE,
				)
			);
			$patterns[$i] = "|\[video-ooyala:".$match."]|";
			$video_replace[$i] = theme('ooyala_thumbnail', array('embed_code' => $item['value'], 'preset' => $preset, 'link_href' => $link_url, 'link_attributes' => array('class' => array('colorbox-load'))));
			$i++;
		}
	}

	if (!empty($matches_player[0])){
		$matches_player = $matches_player[0];

		foreach($matches_player as $match_player) {
			drupal_add_js(drupal_get_path('module', 'ooyala') . '/ooyala_player.js');
			$now = time(now);
			$match_player = substr($match_player, 21,-1);
			$node_match_player = node_load($match_player);
			$item_player = isset($node_match_player->field_ooyala_video) ? $node_match_player->field_ooyala_video['und'][0] : NULL;
			$preset = NULL;
			$embed_code = $item_player['value'];
			$container_id = $now+$i;
			$container_id = 'ooyala-container-'.$container_id;
			$params = array(
				'playerId' => 'field_ooyala_video_0_ooyala_player' . rand(),
				'height' => 300,
				'width' => 400,
				'embedCode' => $item_player['value'],
				'playerContainerId' => $container_id,
				'wmode' => 'transparent',
				'callback' => 'receiveOoyalaEvent'
			);
			$patterns[$i] = "|\[video-ooyala-player:".$match_player."]|";
			$video_replace[$i] = '<div id="' . $container_id . '"></div><script type="text/javascript" src="http://player.ooyala.com/player.js?' . htmlspecialchars(http_build_query($params)) . '"></script>';
			$i++;
		}
	}

	if(!empty($patterns) || !empty($video_replace)){
		$node->content['body'][0]['#markup'] = preg_replace($patterns,$video_replace,$node_content);
	}
}
