<?php

/**
 * @file
 * Enhanced control over the weight any Block.
 *
 * Block Weight allows users to add weights to any block through the block's
 * configuration interface.
 */

/**
 * Implements hook_permission().
 */
function block_weight_permission() {
  return array(
    'administer block weight' => array(
      'title' => t('Administer block weight'),
      'description' => t('Set weight for blocks.'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * Alter block edit form to add configuration field.
 */
function block_weight_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('administer block classes') && ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form')) {

    // Load statically cached block object used to display the form.
    $block = block_load($form['module']['#value'], $form['delta']['#value']);

    $form['settings']['block_weight'] = array(
      '#type' => 'textfield',
      '#title' => t('Block Weight'),
      '#default_value' => isset($block->weight) ? $block->weight : '',
      '#description' => t('Position the block by manually adjusting the weight.'),
      '#maxlength' => 255,
    );

    $form['#submit'][] = 'block_weight_form_submit';
  }
}

/**
 * Helper function: additional submit callback for block configuration pages.
 *
 * Save supplied block weight.
 */
function block_weight_form_submit($form, &$form_state) {
  if ($form_state['values']['form_id'] == 'block_admin_configure' || $form_state['values']['form_id'] == 'block_add_block_form') {

    // Only save if value has changed.
    if (isset($form_state['values']['block_weight']) && $form['settings']['block_weight']['#default_value'] != $form_state['values']['block_weight'] && user_access('administer blocks')) {
      db_update('block')
        ->fields(array('weight' => $form_state['values']['block_weight']))
        ->condition('module', $form_state['values']['module'])
        ->condition('delta', $form_state['values']['delta'])
        ->execute();
      // Flush all context module cache to use the updated block weight.
      if (module_exists('context')) {
        cache_clear_all('context', 'cache', TRUE);
      }
    }
  }
}
