<?php

/**
 * @file ebay_issue_conditional/ebay_issue_conditional.module
 */

/*
 * Implements hook_page_alter().
 */
function ebay_issue_conditional_page_alter(&$page) {
  if (isset($page['content']['system_main']['type']['#value']) && $page['content']['system_main']['type']['#value'] == 'issue' && $page['content']['system_main']['type']['#id'] == 'edit-type') {
    drupal_add_js(drupal_get_path('module', 'ebay_issue_conditional') . '/js/ebay_issue_conditional.js');
  }
}