<?php

/**
 * Implementation of hook_install().
 */
function node_export_push_install() {
  drupal_install_schema('node_export_push');
}

/**
 * Implementation of hook_schema().
 */
function node_export_push_schema() {
  return array();
}

/**
 * Implementation of hook_uninstall().
 */
function node_export_push_uninstall() {
  variable_del('node_export_push_destination');
  variable_del('node_export_push_destination_name');
  drupal_uninstall_schema('node_export_push');
}
