<?php
// $Id: mni_dashboard.module,v 1 2011/04/12 14:41:03 jc Exp $

/**
 * @file
 * create blocks for each product a user is subscribed to
 * and tracks last viewed sections for the last viewed area by product
 */


/*
*  ---------------------------------------------------------
*  UI section
*  ---------------------------------------------------------
*/

/*
* Implementation of hook_perm().
*/
function mni_dashboard_perm() {
 return array('administer mni_dashboard');
}

/*
* Implementation of hook_help().
*/

function mni_dashboard_help($path, $arg) {
 switch ($path) {
   case 'admin/help#mni_dashboard':
		$message= "<p>This module contains all the blocks for the dashboard page</p>";
		return $message;
		break;
 }
}


/**
 *
 * hook_block() implementation
 */
function mni_dashboard_block($op = 'list', $delta = 0, $edit = array()) {
	global $user;
	  switch ($op) {
	    // for admin/system/block
	    case 'list' :
	      $block['mni_dashboard_mainwire']['info'] = t('Dashboard: MNI Main Wire');
	      $block['mni_dashboard_asiamainwire']['info'] = t('Dashboard: MNI Asia Main Wire');
	      $block['mni_dashboard_cobullets']['info'] = t('Dashboard: MNI Commodities Bullets');
	      $block['mni_dashboard_credit']['info'] = t('Dashboard: MNI Credit Bullet Points');
	      $block['mni_dashboard_eqbullets']['info'] = t('Dashboard: MNI Equities Bullets');
	      $block['mni_dashboard_fibullets']['info'] = t('Dashboard: MNI Fixed Income Bullets');
	      $block['mni_dashboard_fxbullets']['info'] = t('Dashboard: MNI Foreign Exchange Bullets');
	      $block['mni_dashboard_oracleessay']['info'] = t('Dashboard: MNI Connect');

	      $block['mni_dashboard_fxpackagebasic']['info'] = t('Dashboard: MNI Foreign Exchange Package Basic');
	      $block['mni_dashboard_fxpackageselect']['info'] = t('Dashboard: MNI Foreign Exchange Package Select');
	      $block['mni_dashboard_fxpackageprime']['info'] = t('Dashboard: MNI Foreign Exchange Package Prime');
	      $block['mni_dashboard_fipackagebasic']['info'] = t('Dashboard: MNI Fixed Income Package Basic');
	      $block['mni_dashboard_fipackageselect']['info'] = t('Dashboard: MNI Fixed Income Package Select');
	      $block['mni_dashboard_mnimonitor']['info'] = t('Dashboard: MNI Monitor');

	      return $block;
	    break;
	    case 'view' :
	      // return block content
				$show_block=false;
	      $block['subject'] = $delta;
	      $block['content'] = array();
				$product_data=get_product_data($delta);
			  if (count(array_intersect($product_data['required_role'], array_values($user->roles)))) {
			  	$show_block=true;
		    	$product_name=$product_data['product_name'];
		    	$product_url_name=$product_data['product_url_name'];
		    	$launch_url=$product_data['launch_url'];
			$launch_w=(isset($product_data['launch_w']) ? $product_data['launch_w'] : 825);
			$launch_h=(isset($product_data['launch_h']) ? $product_data['launch_h'] : 825);
			$launch_js="return openpopup('$launch_url',$launch_w,$launch_h);";
		    	$tabs = $product_data['tabs'];
					foreach ($tabs as &$tab){
						$tab['tab_item_count']=0;
						foreach ($tab['menus'] as $menu){
			    		$temp=_mni_dashboard_simple_links(menu_navigation_links($menu[0]), $menu[1]);
			    		$tab['menu_links'][]=$temp['links'];
			    		$tab['tab_item_count']+=$temp['count'];
						}
					}
	    	}else{ //not role member
					$show_block=false;
	    	}

		if($show_block){
			$block['content'] = theme('dashboard_product', $product_name, $product_url_name, $launch_url, $tabs, $launch_js);
		}else{
			$block['content'] = NULL;
		}

	      return $block;
	    break;
	    default :
	  }

}

/**
 * Implementation of hook_theme().
 */
function mni_dashboard_theme() {
  return array(
    'dashboard_product' => array(
      'arguments' => array('product_name' => NULL, 'product_url_name'=> NULL, 'launch_url' => NULL, 'tabs' => array(), 'launch_js' => NULL),
      'template' => 'dashboard_product',
    ),
  );
}

function _mni_dashboard_simple_links($links, $hdr=null, $popup=true) {
	if ($hdr){
		$output="<li class='subhed'>".$hdr."</li>";
	} else {
		$output="";
	}
	$c=0;
	foreach ($links as $link_item) {
    // Check to see if it is a visible menu item.
    if (!isset($link_item['hidden']) || $link_item['hidden'] == 0) {
      $c++;
      $clean_path = str_replace(array('http://', 'www', '<', '>', '&', '=', '?', ':', '.'), '', $link_item['href']);
      // Convert slashes to dashes.
      $clean_path = str_replace('/', '-', $clean_path);
	if($popup || (isset($link_item['popup']) && $link_item['popup'])){
		$width = 800;
		$height = 825;
		$output .= '<li><a href="'.$link_item['href'].'" onclick="return openpopup(\''
			.$link_item['href'].'\','.$height.','.$width.');" target="_blank">'.$link_item['title'].'</a></li>';
	}else{
		$output .= '<li><a href="'.$link_item['href'].'" >'.$link_item['title'].'</a></li>';
	}

    }
  }
	return array('count'=>$c,'links'=>$output);
}

function mni_dashboard_tracker($product_url_name,$term_name){
	/*
	called by page-subscription_articles.tpl.php
	tracks last viewed dashboard menu items by uid and tid

	table mni_dashboard_last_viewed
		uid
		tid (taxonomy term id)
		product - store as product name from url -- both the list page and the dashboard page(?) have access to
		viewed_date - defaults to current timestamp on insert and update

		check if uid tid exists - if so update date
			if not, insert

		also need something to display the results - ...
	*/
	global $user;


	$term=taxonomy_get_term_by_name(str_replace('-',' ',$term_name));
	$tid=$term[0]->tid;

	if($tid && $product_url_name){
		$sql = "INSERT INTO mni_dashboard_last_viewed (uid,tid,product) VALUES (%d,%d,'%s')
		  ON DUPLICATE KEY UPDATE product='%s',viewed_date=default;
		";
		$result = db_query($sql, $user->uid, $tid,$product_url_name,$product_url_name);
}
}

function mni_dashboard_display_last_viewed($product_url_name){
	/*
	called by dashboard_product.tpl.php
	display up to 5 last viewed taxonomy terms (menu items) in this product
	*/
	global $user;

	$sql = "SELECT td.name from mni_dashboard_last_viewed lv join term_data td on lv.tid=td.tid where lv.uid =%d and lv.product='%s' order by viewed_date desc limit 5";

	$result = db_query($sql, $user->uid,$product_url_name);
	while ($row= db_fetch_array($result)) {
		$items[]= array("title"=>$row[name], "href"=>"/subscription_articles/".$product_url_name."/".str_replace(' ', '-', $row[name]));
	}

	if(count($items)) {
		$links=_mni_dashboard_simple_links($items);
	  return $links["links"];
	}
}




function get_product_data($delta){
  switch ($delta) {
    case 'mni_dashboard_mainwire' :
    	$product_data=array(
    		required_role=>array("mainwire"),
    		product_name=>"MNI Main Wire",
    		product_url_name=>"Main-Wire",
    		//launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=https%3A%2F%2Fmninews.deutsche-boerse.com%2Frtmw&sso_b=MNIA",
    		launch_url=>"/realdisplay?product=MW",

		launch_w=>650,

    		tabs=>array(
    			array(
	    			tab_name=>'News',
	    			tab_machine_name=>'tab_mw_news',
		    		menus=>array(
		    			array('menu-mainwire',''),
		    		),
	    		),
    			array(
	    			tab_name=>'Markets',
	    			tab_machine_name=>'tab_mw_markets',
		    		menus=>array(
		    			array('menu-main-wire-markets',''),
		    		),
		    	),
	    		array(
	    			tab_name=>'Central Banks',
	    			tab_machine_name=>'tab_mw_banks',
		    		menus=>array(
		    			array('menu-main-wire-central-banks',''),
		    		),
		    	),
	    		array(
	    			tab_name=>'Region',
	    			tab_machine_name=>'tab_mw_region',
		    		menus=>array(
		    			array('menu-news-index-by-region-europe','Europe'),
	    				array('menu-american-news-index','Americas'),
	    				array('menu-asia-index-menu','Asia'),
		    		),
		    	),
					array(
	    			tab_name=>'Calendars',
	    			tab_machine_name=>'tab_mw_calendars',
		    		menus=>array(
		    			array('menu-calendars',''),
		    		),
		    	),
	    		array(
	    			tab_name=>'Economic indicators',
	    			tab_machine_name=>'tab_mw_indicators',
		    		menus=>array(
							array('menu-australia-indicators','Australia'),
							array('menu-china-indicators','China'),
							array('menu-eurozone-indicators','Eurozone'),
							array('menu-france-indicators-mw','France'),
							array('menu-germany-indicators-mw','Germany'),
							array('menu-italy-indicators','Italy'),
							array('menu-japan-indicators','Japan'),
							array('menu-new-zealand-indicators-mw','New Zealand'),
							array('menu-spain-indicators-mw','Spain'),
							array('menu-uk-indicators-mw','UK'),
							array('menu-united-states-indicators-mw','United States'),
							array('menu-canada-indicators-mw','Canada'),
		    		),
		    	),
		    ),
    	);
    break;
    case 'mni_dashboard_credit' :
    	$product_data=array(
    		required_role=>array("credit"),
    		product_name=>"MNI Credit Bullet Points",
    		product_url_name=>"Credit-Bullets",
    		//launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=https%3A%2F%2Fmninews.deutsche-boerse.com%2Frtcb&sso_b=MNIA",
    		launch_url=>"/realdisplay?product=CB",

		launch_w=>650,

    		tabs=>array(
    			array(
	    			tab_name=>'Credit Features',
	    			tab_machine_name=>'tab_cb_features',
		    		menus=>array(
		    			array('menu-markets-cb','Markets'),
		    			array('menu-central-bank-information-cb','Central Bank Information'),
		    			array('menu-news-calendars-cb','News Calendars'),
		    		),
	    		),
    			array(
	    			tab_name=>'Economic Indicators',
	    			tab_machine_name=>'tab_cb_ec_ind',
		    		menus=>array(
		    			array('menu-uk-indicators-cb','UK'),
		    			array('menu-united-states-indicators-cb','United States'),
		    			array('menu-c-c-j-indicators-cb','Canada/China/Japan'),
		    		),
	    		),
	    	),
	   	);
    break;
    case 'mni_dashboard_fibullets' :
    	$product_data=array(
    		required_role=>array("fibullets"),
    		product_name=>"MNI Fixed Income Bullets",
    		product_url_name=>"Fixed-Income-Bullets",
    		//launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=https%3A%2F%2Fmninews.deutsche-boerse.com%2Frtfi&sso_b=MNIA",
    		launch_url=>"/realdisplay?product=FI",

		launch_w=>650,

    		tabs=>array(
    			array(
	    			tab_name=>'Fixed Income Features',
	    			tab_machine_name=>'tab_fi_features',
		    		menus=>array(
		    			array('menu-markets-fi','Markets'),
		    			array('menu-central-bank-information-fi','Central Bank Information'),
		    			array('menu-news-calendars-fi','News Calendars'),
		    		),
	    		),
    			array(
	    			tab_name=>'Economic Indicators',
	    			tab_machine_name=>'tab_fi_ec_ind',
		    		menus=>array(
		    			array('menu-uk-indicators-fi','UK'),
		    			array('menu-united-states-indicators-fi','United States'),
		    			array('menu-c-c-j-indicators-fi','Canada/China/Japan'),
		    		),
	    		),
	    	),
	   	);
    break;
    case 'mni_dashboard_fxbullets' :
    	$product_data=array(
    		required_role=>array("fxbullets"),
    		product_name=>"MNI Foreign Exchange Bullets",
    		product_url_name=>"Foreign-Exchange-Bullets",
    		//launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=https%3A%2F%2Fmninews.deutsche-boerse.com%2Frtfx&sso_b=MNIA",
    		launch_url=>"/realdisplay?product=FX",

		launch_w=>650,

    		tabs=>array(
    			array(
	    			tab_name=>'FX Features',
	    			tab_machine_name=>'tab_fx_features',
		    		menus=>array(
		    			array('menu-markets-fx','Markets'),
		    			array('menu-central-bank-information-fx','Central Bank Information'),
		    			array('menu-news-calendars-fx','News Calendars'),
		    		),
	    		),
    			array(
	    			tab_name=>'Economic Indicators',
	    			tab_machine_name=>'tab_fx_ec_ind',
		    		menus=>array(
		    			array('menu-uk-indicators-fx','UK'),
		    			array('menu-united-states-indicators-fx','United States'),
		    			array('menu-c-c-j-indicators-fx','Canada/China/Japan'),
		    		),
	    		),
	    	),
	   	);
    break;
    case 'mni_dashboard_cobullets' :
    	$product_data=array(
    		required_role=>array("cobullets"),
    		product_name=>"MNI Commodities Bullets",
    		product_url_name=>"Commodities-Bullets",
    		launch_url=>"/realdisplay?product=CO",

		launch_w=>650,

    		tabs=>array()
	   	);
    break;
    case 'mni_dashboard_eqbullets' :
    	$product_data=array(
    		required_role=>array("eqbullets"),
    		product_name=>"MNI Equities Bullets",
    		product_url_name=>"Equities-Bullets",
    		launch_url=>"/realdisplay?product=EQ",

		launch_w=>650,

    		tabs=>array()
	   	);
    break;
    case 'mni_dashboard_asiamainwire' :
      $product_data = array(
        required_role    => array("asiamainwire"),
        product_name     => "MNI Asia Main Wire",
        product_url_name => "Main-Wire-Asia",
        launch_url       => "/realdisplay?product=AMW",
        launch_w         => 650,
        tabs => array()
      );
    break;
    case 'mni_dashboard_fxpackagebasic' :
    	$product_data=array(
    		required_role=>array("fxpackage"),
    		product_name=>"MNI FX Basic",
    		product_url_name=>"",
    		launch_url=>"https://mni.deutsche-boerse.com/fx-basic",

		launch_w=>650,

     		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_fxpackageselect' :
    	$product_data=array(
    		required_role=>array("fxpackageselect"),
    		product_name=>"MNI FX Select",
    		product_url_name=>"",
    		launch_url=>"https://mni.deutsche-boerse.com/fx-select",

		launch_w=>650,

    		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_fxpackageprime' :
    	$product_data=array(
    		required_role=>array("fxpackageprime"),
    		product_name=>"MNI FX Prime",
    		product_url_name=>"",
    		launch_url=>"https://mni.deutsche-boerse.com/fx-prime",

		launch_w=>650,

    		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_fipackagebasic' :
    	$product_data=array(
    		required_role=>array("fipackage"),
    		product_name=>"MNI Fixed Income Basic",
    		product_url_name=>"",
    		launch_url=>"https://mni.deutsche-boerse.com/fi-basic",

		launch_w=>650,

    		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_fipackageselect' :
    	$product_data=array(
    		required_role=>array("fipackageselect"),
    		product_name=>"MNI Fixed Income Select",
    		product_url_name=>"",
    		launch_url=>"https://mni.deutsche-boerse.com/fi-select",

		launch_w=>650,

    		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_mnimonitor' :
    	$product_data=array(
    		required_role=>array("AFM"),
    		product_name=>"MNI Monitor",
    		product_url_name=>"",
    		/*launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=http%3A%2F%2Fmni10-1-2-215.marketnews.com%2Frtafm&sso_b=MNIA",*/
    		launch_url=>"/realdisplay?product=AFM",

    		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_oracleessay' :
    	$product_data=array(
    		required_role=>array("oracleessay"),
    		product_name=>"MNI Connect",
    		product_url_name=>"",
    		launch_url=>"/files/oracle-essay",
    		tabs=>array(),
	   	);
    break;
/*
    case 'mni_dashboard_email' :
    	$product_data=array(
    		required_role=>array("email_credit_pro","email_credit_retail","email_fipackage_pro","email_fipackage_retail","email_fxpackage_pro","email_fxpackage_retail"),
    		product_name=>"MNI Email Services",
    		product_url_name=>"",
    		launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=https%3A%2F%2Fmninews.deutsche-boerse.com%2Frtmw&sso_b=MNIA",
    		tabs=>array(),
	   	);
    break;
    case 'mni_dashboard_screamaudio' :
    	$product_data=array(
    		required_role=>array("screamaudio"),
    		product_name=>"SCREAM Audio",
    		product_url_name=>"",
    		launch_url=>"https://sso.deutsche-boerse.com/cas/activateAndLogin?service=https%3A%2F%2Fmninews.deutsche-boerse.com%2Frtmw&sso_b=MNIA",
    		tabs=>array(),
	   	);
    break;
*/
    default :
    	$product_data=array(
    		required_role=>array(),
    		product_name=>"",
    		product_url_name=>"",
    		launch_url=>"",
    		tabs=>array(),
    		launch_url=>"",
    		tabs=>array(),
	   	);
    break;
	}
	return $product_data;
}
