<?php
/**
 * Implements hook_uninstall().
 */
function re_socialtools_uninstall() {
  variable_del('re_socialtools_fb_api_id');
  variable_del('re_socialtools_social_share_fb_post');
  variable_del('re_socialtools_social_share_fb_title');
  variable_del('re_socialtools_social_share_fb_url');
  variable_del('re_socialtools_social_share_fb_image');
  variable_del('re_socialtools_social_share_twitter_tweet');
  variable_del('re_socialtools_social_share_twitter_hashtags');
  variable_del('re_socialtools_social_share_twitter_url');
}
