<?php
/**
 * @file
 * Main file for apigee_signin_signup module.
 */

/**
 * Implements hook_menu().
 */
function apigee_signin_signup_menu() {
  $items = array();

  $items['admin/config/system/signin-signup'] = array(
    'title' => 'Apigee SignIn/SignUp settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apigee_signin_signup_settings_form'),
    'access arguments' => array('administer content types'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements menu callback.
 *
 * @see apigee_signin_signup_menu()
 */
function apigee_signin_signup_settings_form() {
  global $base_url;
  $current_path = urlencode($base_url . '/' . request_path());

  $form = array();

  $form['settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('SignIn/SignUp settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['settings']['sign_in_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Sign In URL'),
    '#default_value' => variable_get("sign_in_url", '/about/sign-in?origin=' . $current_path),
    '#size' => 100,
    '#maxlength' => 200,
    '#required' => TRUE,
  );

  $form['settings']['sign_up_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Sign Up URL'),
    '#default_value' => variable_get("sign_up_url", '/about/sign-up?origin=' . $current_path),
    '#size' => 100,
    '#maxlength' => 200,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}