<?php

/**
 * Implementation of hook_block_info()
 */
function ebay_regionality_block_info() {
  $blocks['ebay_regionality_selector'] = array(
    'info' => t('eBay Region Selector'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view()
 */
function ebay_regionality_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'ebay_regionality_selector':
      $block['subject'] = t('Select your region');
      $block['content'] = drupal_get_form('ebay_regionality_regions_form');
      break;
  }
  return $block;
}

/**
 * Build the region links
 */
function ebay_regionality_regions_form($form, &$form_submit) {
  $form = array();
  $options = array(
    'global' => t('Global'),
    'united-states' => t('United States'),
    'asia-pacific' => t('Asia Pacific'),
    'australia' => t('Australia'),
    'europe' => t('Europe')
  );
  $form['ebay_regionality_regions'] = array(
    '#type' => 'select',
    '#options' => $options,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
  );

  return $form;
}

function ebay_regionality_regions_form_submit($form, &$form_submit) {
  setcookie('ebay_region', $form_submit['values']['ebay_regionality_regions']);
  _ebay_regionality_direct_traffic();
}

/**
 * Implementation of hook_init()
 *
 * If ebay_region cookie is set attempt to match the current page request with the correct region
 */
function ebay_regionality_init() {
  drupal_add_js('misc/jquery.form.js');
  drupal_add_library('system', 'drupal.ajax');
  _ebay_regionality_direct_traffic();
}

function _ebay_regionality_direct_traffic() {        
	$local_urls = array('region', 'about', 'issues', 'news');
	$regions = array('global', 'united-states', 'asia-pacific', 'australia', 'europe');
	$path_params = explode('/', $_SERVER['REQUEST_URI']);

	if (isset($_COOKIE['ebay_region'])) {
		if ($path_params[1] == '') { // If this is the front page
			if ($_COOKIE['ebay_region'] != 'global') {
				// Localize the front page if the region is not "global"
				$newURL = 'region/' . $_COOKIE['ebay_region'];
				drupal_goto($newURL);
			}
		}
    else if (in_array($path_params[1], $local_urls)) {
			// If not global region OR the 2nd path argument is not a region, don't localize.
			if ($_COOKIE['ebay_region'] == 'global' || (isset($path_params[2]) && !in_array($path_params[2], $regions))) {
				return;
			}
			// Localize request
			if (!in_array($_COOKIE['ebay_region'], $path_params)) {
				$newURL = _ebay_regionality_localize_url($_SERVER['REQUEST_URI'], $_COOKIE['ebay_region']);
			}
		}
	}
  if (isset($newURL)) {
    drupal_goto($newURL);
  }
  return;
}

/**
 * Parse the referrering URL and go to the new URL based on the region.
 */
function _ebay_regionality_localize_url($referrer, $region) {
	$regions = array('global', 'united-states', 'asia-pacific', 'australia', 'europe');
	$local_urls = array('region', 'about', 'issues', 'news');

	$path = explode('/', $referrer);
	$directories = count($path);
	$newURL = '';

	if ($region == 'global') {

		// "global" is a special case. If that region is selected then pages with no region are used
		$base = $path[1];
		switch ($base) {
			case '':
			case 'node':
				$newURL = '<front>';
				break;
			case 'news':
			case 'issues':
			case 'team':
			case 'about':
				$newURL = $base;
				break;
		}
		return $newURL;

	}

	if ($directories <= 2)	{
		// Paths with only one level
		$base = $path[1];
		switch ($base) {
			case '':
			case 'node':
				// we're at the homepage so add the region filter to it
				$newURL = 'region/' . $region;
				break;
			case 'news':
			case 'issues':
			case 'team':
				// second level pages that are really views with a region filter... so add it
				$newURL = $base . '/' . $region;
				break;
			case 'about':
				$newURL = $base . '/region/' . $region;
				break;
			default:
				// second level pages that have no need for a region filter...so add the filter to the homepage
				$newURL = 'region/' . $region;

			}

	} else if ($directories > 2)	{

		// Paths with two or more levels
		$base = $path[1];

		// third level pages and beyond are assumed to be nodes and not views,
		// so we will either travel to a second level section filtered by region,
		switch ($base) {
			case 'news':
			case 'issues':
			case 'team':
				$newURL = $base . '/' . $region;
				break;
			case 'about':
				$newURL = $base . '/region/' . $region;
				break;
			default: // or the homepage filtered by region
				$newURL = 'region/' . $region;
		}

	}

	return $newURL;

}


/**
 * Set the 'ebay_region' cookie.
 *
 * Called by a POST in region_filter.js when the user selects a region from the drop down.

function ebay_regionality_set_region($region = '') {
	$allowed_regions = array('global', 'united-states', 'asia-pacific', 'australia', 'europe');
	if (isset($region) && in_array($region, $allowed_regions)) {
		setcookie('ebay_region', $region, time()+(31536000), '/'); // Save for 1 year
		print 'true';
		exit;
	}
	print 'false';
	exit;
}
 */