<?php

require_once(dirname(__FILE__)."/lib/vendor/autoload.php");

use Symfony\Component\Yaml\Yaml;


function apigee_menus_theme() {
  return array(
    "apigee_menus_file_list" => array(
      "variables" => array(
        "path" => null,
        "files" => array()
      )
    ),
    "apigee_menus_view_yaml_link" => array(
    "variables" => array(
      "type" => "default",
      "file" => array()
      )
    ),
    "apigee_menus_view_yaml_file" => array(
    "variables" => array(
      "file" => array()
      )
    ),
    "apigee_menus_env_link_data" => array(
      "variables" => array(
        "data" => array()
        )
      )
    );
}

function apigee_menus_menu() {
  $items = array();

  $items['admin/structure/apigee-menus'] = array(
    'title'            => 'Apigee Menus',
    'description'      => 'Export Apigee Menu to YAML.',
    'access arguments' => array('administer menu'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('apigee_menus_menu_list'),
  );
  $items['admin/structure/apigee-menus/list'] = array(
    'title' => 'Export menus',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/apigee-menus/overrides'] = array(
    'title' => 'Overrides',
    'type' => MENU_LOCAL_TASK,
    'description'      => 'List apigee menus that are overridden by files in the private:// filesystem.',
    'page callback'    => 'apigee_menus_overrides_list',
    'access arguments' => array('administer menu'),
    'weight' => 0,
  );
  $items['admin/structure/apigee-menus/defaults'] = array(
    'title' => 'Defaults',
    'type' => MENU_LOCAL_TASK,
    'description'      => 'List apigee menus defaults for this enviornment.',
    'page callback'    => 'apigee_menus_defaults_list',
    'access arguments' => array('administer menu'),
    'weight' => 0,
  );
  $items['admin/structure/apigee-menus/defaults/list'] = array(
    'title' => 'Default Files',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/apigee-menus/yaml/view/%/%'] = array(
    'title' => 'View YAML file Contents',
    'type' => MENU_CALLBACK,
    'description'      => 'View the contents of a YAML File',
    'page callback'    => 'apigee_menus_yaml_view',
    'page arguments'   => array(5,6),
    'access arguments' => array('administer menu'),
    'weight' => 0,
  );
  return $items;
}



function apigee_menus_menu_list($form, &$form_state) {
  $form['header'] = array(
    "#type" => "markup",
    "#markup" => "<h1>Export a menu as YAML</h1>"
  );

  $menus = menu_get_menus();
  $form['menus'] = array(
    "#type" => "select",
    "#options" => $menus,
  );

  $form['actions'] = array(
      '#weight' => 100,
    );
  $form['actions']['download'] = array(
    '#type' => 'submit',
    '#value' => t('Download'),
  );

  return $form;
}

function apigee_menus_overrides_list() {
  $dir = "private://config/active";
  $files = file_scan_directory($dir, '/.yml/', array("key" => "filename"));
  return theme("apigee_menus_file_list", array("path" => $dir, "files" => $files));
}

function apigee_menus_defaults_list() {
  $dir = drupal_get_path("module", "apigee_menus")."/config";
  $files = file_scan_directory($dir, '/.yml/', array("key" => "filename"));
  return theme("apigee_menus_file_list", array("path" => $dir, "files" => $files));
}

function apigee_menus_defaults_menu($location, $name) {

}

function apigee_menus_menu_list_submit($form, &$form_state) {
  $file = apigee_menus_save($form_state['values']['menus']);
  $filename = @array_pop(explode("/", $file));
  $headers = file_get_content_headers($file);
  $headers['Content-Disposition'] = "attachment; filename={$filename}";
  file_transfer($file, $headers);
}


function apigee_menus_save($menu_name = "main-menu") {
  if (!array_key_exists('AH_SITE_ENVIRONMENT', $_ENV)){
    $_ENV['AH_SITE_ENVIRONMENT'] = "local";
  }
  module_load_include("module", "d8cmi");
  d8cmi_init();
  $main_menu_tree = menu_tree('main-menu');
  $main_menu_tree['#attributes']['class'][] = 'nav';
  $main_menu_tree['#attributes']['id'][] = 'main-menu';
  // We change the wrapper theme, to the one that supports attributes.
  $main_menu_tree['#theme_wrappers'][0] = 'menu_tree_top_main';
  $config = Drupal::config("apigee_menus.{$menu_name}.settings");
  $config->set($_ENV['AH_SITE_ENVIRONMENT'], $main_menu_tree);
  return $config->save();
}


function apigee_menus_load($menu_name = "main_menu") {
  if (!array_key_exists('AH_SITE_ENVIRONMENT', $_ENV)){
    $_ENV['AH_SITE_ENVIRONMENT'] = "local";
  }
  module_load_include("module", "d8cmi");
  d8cmi_init();
  $config = Drupal::config("apigee_menus.{$menu_name}.settings");
  return  $config->get($_ENV['AH_SITE_ENVIRONMENT']);
}

function apigee_menus_yaml_view($location, $name) {
  drupal_add_library('system', 'ui.tabs');
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Administration', 'admin');
  $breadcrumb[] = l('Structure', 'admin/structure');
  $breadcrumb[] = l('Apigee Menus', 'admin/structure/apigee-menus');
  $section = ($location == "private")?"overrides":"default";
  $breadcrumb[] = l(ucwords($section), 'admin/structure/apigee-menus/'.$section);
  $breadcrumb[] = drupal_get_title();
  $breadcrumb[] = $name;
  drupal_set_breadcrumb($breadcrumb);

  module_load_include("module", "d8cmi");
  d8cmi_init();
  $scheme = ($location == "default")?
      drupal_get_path("module", "apigee_menus")."/config":"private://config/active";
  return theme("apigee_menus_view_yaml_file", array("file" => YAML::parse(file_get_contents(drupal_realpath($scheme)."/{$name}.yml"))));
}


function theme_apigee_menus_file_list($vars) {
  $rows = array();
  $parsed = parse_url($vars['path']);
  foreach ($vars['files'] as $file) {
    $rows[] = array(
        $file->filename,
        theme("apigee_menus_view_yaml_link", array("file" => $file, "type" => ($parsed['scheme'])?$parsed['scheme']:"default"))
      );
  }
  return theme("table", array("header" => array(array("data" => $vars['path'], 'colspan' => 2)), "rows" =>$rows));
}

function theme_apigee_menus_view_yaml_link($vars) {
  //return "<pre>".print_r(func_get_args(), true)."</pre>";
  return l("view", "admin/structure/apigee-menus/yaml/view/".$vars['type']."/".$vars['file']->name);
}

function theme_apigee_menus_view_yaml_file($vars) {
  $toReturn = "<div id='apigee-menus-view-yaml-file-tabs'><ul>";
  $tabs = "";
  foreach($vars['file'] as $env => $data) {
    $toReturn .= "<li><a href='#env-{$env}'><span>{$env}</span></a></li>";
    $tabs .= "<div id='env-{$env}'>".theme("apigee_menus_env_link_data", array("data" => $data))."</div>";
  }
  $toReturn .= "</ul>".$tabs."</div>";
  $toReturn .= "<script>jQuery('#apigee-menus-view-yaml-file-tabs').tabs();</script>";
  return $toReturn;
}

function theme_apigee_menus_env_link_data($vars){
  //return "<pre>".print_r(func_get_args(), true)."</pre>";
  $toReturn = "<ul>";
  foreach($vars['data'] as $key => $link) {
    if (is_numeric($key)) {
      $toReturn .= "<li><b>". $link['#title']."</b>&nbsp;(".l($link['#href'], $link['#href']).")";
      if (!empty($link['#below'])) {
        $toReturn .= theme_apigee_menus_env_link_data(array("data" => $link['#below']));
      }
      $toReturn .= "</li>";
    }
  }
  $toReturn .= "</ul>";
  return $toReturn;
}