<?php

/**
 * @file
 * Contains momentum_officials.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function momentum_officials_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the momentum_officials module.
    case 'help.page.momentum_officials':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the ability to find elected officials based on location using the Momentum API.') . '</p>';
      return $output;

    default:
  }
}
