<?php
/**
 * @file
 * svcf_infograph.module
 */

/**
 * Implements hook_block_info().
 */
function svcf_infograph_block_info() 
{
    $blocks['infograph'] = array(
    'info' => t('Homepage Infographic'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function svcf_infograph_block_view($delta = 0) 
{
    global $base_url;

    $block = array();

    $path = drupal_get_path('module', 'svcf_infograph');

    if (($delta == 'infograph') && ($content = file_get_contents($path . '/svcf_infograph.inc'))) {
        $content = str_replace('SVCF_INFOGRAPH_ROOT', $base_url . '/' . $path, $content);

        $block['subject'] = null;
        $block['content'] = array(
        '#markup' => $content,
        '#attached' => array(
        'js' => array(
          $path . '/scripts/vendor.js' => array('type' => 'file'),
          $path . '/scripts/main.js' => array('type' => 'file'),
        ),
        'css' => array(
          // '//fonts.googleapis.com/css?family=Open+Sans:400,300,600' => array('type' => 'external'),
          '//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css' => array('type' => 'external'),
          $path . '/styles/vendor.css' => array('type' => 'file'),
          $path . '/styles/main.css' => array('type' => 'file'),
        ),
        ),
        );
    }

    return $block;
}
