<section class="footer">
  <footer class="container">
    <div class="row">
      <div class="col-md-9">
        <p class="disclaimer">Msg&amp;data rates may apply in the US. Standard message and data rates apply in Canada. To unsubscribe from an EZ Texting ® list, simply text ‘STOP’ to the originating short code or <a href="https://www.eztexting.com/help">contact Support</a>.</p>
        <p class="disclaimer">&copy; CallFire Inc. <?php echo date("Y") ?>. EZ Texting neither provides lists of phone numbers nor do we access our clients' contact lists.<br>
        EZ Texting is a 100% opt-in service. Please see our <a href="<?php print base_path(); ?>privacy-policy" rel="nofollow">Privacy Policy</a>, <a href="<?php print base_path(); ?>terms" rel="nofollow">Terms Of Use</a> &amp; <a href="<?php print base_path(); ?>anti-spam-policy" rel="nofollow">Anti-Spam Policy</a> to learn about our position on SPAM and the privacy of your data. </p>
        <p class="disclaimer">EZ Texting is part of the trusted <a href="https://www.callfire.com">CallFire</a> family of companies.</p>
      </div>
      <div class="footer-brand col-md-3">
        <p class="social"><a href="https://www.facebook.com/EzTexting"><i class="fa fa-facebook"></i></a> <a href="https://twitter.com/EzTexting"><i class="fa fa-twitter"></i></a> <a href="https://plus.google.com/104053580645373212760"><i class="fa fa-google-plus"></i></a></p>
      </div>
    </div>

  </footer>
</section>
