<footer class="purp-footer">
  <div class="footer-top">
    <div class="footer-links">
      <div class="links-purple">
        <h3 class="link-title">About EZ Texting</h3>
        <?php print theme('links', array('links' => menu_navigation_links('menu-about')));?>
      </div>
      <div class="links-purple">
        <h3 class="link-title">Resources</h3>
        <?php print theme('links', array('links' => menu_navigation_links('menu-resources')));?>
      </div>
      <div class="links-purple">
        <h3 class="link-title">Help / Contact</h3>
        <?php print theme('links', array('links' => menu_navigation_links('menu-help-contact')));?>
      </div>
      <img class="logo-bw" src="https://www.eztexting.com/sites/default/files/logo-bw.png" alt="logo-bw">
      <div id="social">
          <a href="https://plus.google.com/104053580645373212760"><img src="https://www.eztexting.com/sites/default/files/Google.png" alt="google"></a>
        <!-- <img src="../images/insta.png" alt=""> -->
        <a href="https://twitter.com/EzTexting"><img src="https://www.eztexting.com/sites/default/files/Twitter.png" alt="twitter"></a>
        <a href="https://www.facebook.com/EzTexting"><img src="https://www.eztexting.com/sites/default/files/facebook.png" alt="fb"></a>
      </div>
      <div id="social-mobile">
        <a href="https://www.facebook.com/EzTexting"><img src="https://www.eztexting.com/sites/default/files/fb-mobile.png" alt="fb"></a>
        <a href="https://twitter.com/EzTexting"><img src="https://www.eztexting.com/sites/default/files/twitter-mobile.png" alt="twitter"></a>
        <br>
        <a href="https://plus.google.com/104053580645373212760"><img src="https://www.eztexting.com/sites/default/files/google-mobile.png" alt=""></a>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="bott-left">
      <p>Ez Texting is a 100% opt-in service. Please see our <a href="https://www.eztexting.com/privacy-policy">Privacy Policy,</a> <a href="https://www.eztexting.com/terms">Terms Of Use</a> & <a href="https://www.eztexting.com/anti-spam-policy">Anti-Spam Policy</a> to learn about<br>our position on SPAM and the privacy of your data.</p><br>
      <p>Msg&data rates may apply in the US. Standard message and data rates apply in Canada. To unsubscribe from<br>an EZ Texting ® list, simply text ‘STOP’ to the originating short code or contact <a href="https://www.eztexting.com/help">Support.</a></p>
    </div>
    <div class="bott-right">
      <p class="callfire-inc">Ez Texting is part of the trusted <a href="https://www.callfire.com/?__hstc=211998539.8f56340e8a136e0078448ab33f951eab.1494000256650.1494000256650.1494000256650.1&__hssc=211998539.6.1494000256651&__hsfp=3657549647">CallFire</a> family of companies.<br>© CallFire Inc. 2017</p>
    </div>
  </div>
</footer>
