  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <a href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>" rel="home" class="navbar-brand">
        <img src="<?php print base_path() . path_to_theme() . "/images/ez-texting-logo-white.png"; ?>" alt="<?php print t('Home'); ?>">
      </a>
      <ul class="nav navbar-nav navbar-right">
        <li class="phone-number">Call now! <a href="tel:+18007535732">(800) 753-5732</a></li>
        <li><a class="btn btn-rounded btn-log-in" href="https://app.eztexting.com/">Log In</a></li>
      </ul>
    </div>
  </div>