<?php

/**
 * @file
 *   Basic configuration and tools for BIPAC
 */

/**
 * Implements hook_init()
 */
function bipac_init() {
  drupal_add_css(drupal_get_path('module', 'bipac') . '/css/bipac.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}

/**
 * Implements hook_permission()
 */
function bipac_permission() {
  return array(
    'admin bipac access' => array(
      'title' => t('Administrate BIPAC configuration'),
      'description' => t('Set configuration options for BIPAC'),
    ),
  );
}

/**
 * Helper function to format phone numbers
 */
function bipac_format_phone($number) {
  return preg_replace('~.*(\d{3})[^\d]*(\d{3})[^\d]*(\d{4}).*~', '($1) $2-$3', $number);
}

/**
 * Verify that something is a real URL
 * Modify as necessary
 */
function bipac_checkurl($url, $title = 'link to content', $text = NULL) {
  $content = $url;
  if (preg_match("/^(https|http|ftp)\:\/\/|([a-z0-9A-Z]+\.[a-z0-9A-Z]+\.[a-zA-Z]{2,4})|([a-z0-9A-Z]+\.[a-zA-Z]{2,4})|\?([a-zA-Z0-9]+[\&\=\#a-z]+)/i", $url, $m) != 0) {
    if ($text == NULL) {
      $text = $url;
    }
    // Should probably send this through l
    $content = '<a href = "' . $url . '" title = "' . $title . '" target = "_blank">' . $text . '</a>';
  }
  return $content;
}

/**
 * A handler function for BIPAC session data across modules
 * @args
 *   $key - The storage key to use
 *   $value - The value to associate with that key
 *   $reset - How to handle that key
 * @see
 *   Inline comments for details
 */
function bipac_session($key = NULL, $value = NULL, $reset = FALSE) {
  if ($reset === FALSE) {
    if ((!empty($key)) && (!empty($value))) {
      // Send through a key and value, and load those into session
      // Reset is disregarded
      $_SESSION['bipac_data'][$key] = $value;
      return TRUE;
    }
    elseif ((empty($key)) && (empty($value)) && (!empty($_SESSION['bipac_data']))) {
      return $_SESSION['bipac_data'];
    }
    elseif ((!empty($key)) && (!empty($_SESSION['bipac_data'][$key]))) {
      // Send through just a key and get the value
      // Reset is disregarded
      return $_SESSION['bipac_data'][$key];
    }
    return NULL;	// Return NULL if nothing matches; likely no data in given key
  }
  else {
    if ((!empty($key)) && (empty($value))) {
      // Send through a key and true reset, and clear the key and value
      // Value is disregarded
      unset($_SESSION['bipac_data'][$key]);
    }
    else {
      unset($_SESSION['bipac_data']);
    }
  }
}

/**
 * Get states helper function
 */
function bipac_states() {
  return array(
    'AL'=>"Alabama",
    'AK'=>"Alaska",
    'AZ'=>"Arizona",
    'AR'=>"Arkansas",
    'CA'=>"California",
    'CO'=>"Colorado",
    'CT'=>"Connecticut",
    'DE'=>"Delaware",
    'DC'=>"District Of Columbia",
    'FL'=>"Florida",
    'GA'=>"Georgia",
    'HI'=>"Hawaii",
    'ID'=>"Idaho",
    'IL'=>"Illinois",
    'IN'=>"Indiana",
    'IA'=>"Iowa",
    'KS'=>"Kansas",
    'KY'=>"Kentucky",
    'LA'=>"Louisiana",
    'ME'=>"Maine",
    'MD'=>"Maryland",
    'MA'=>"Massachusetts",
    'MI'=>"Michigan",
    'MN'=>"Minnesota",
    'MS'=>"Mississippi",
    'MO'=>"Missouri",
    'MT'=>"Montana",
    'NE'=>"Nebraska",
    'NV'=>"Nevada",
    'NH'=>"New Hampshire",
    'NJ'=>"New Jersey",
    'NM'=>"New Mexico",
    'NY'=>"New York",
    'NC'=>"North Carolina",
    'ND'=>"North Dakota",
    'OH'=>"Ohio",
    'OK'=>"Oklahoma",
    'OR'=>"Oregon",
    'PA'=>"Pennsylvania",
    'RI'=>"Rhode Island",
    'SC'=>"South Carolina",
    'SD'=>"South Dakota",
    'TN'=>"Tennessee",
    'TX'=>"Texas",
    'UT'=>"Utah",
    'VT'=>"Vermont",
    'VA'=>"Virginia",
    'WA'=>"Washington",
    'WV'=>"West Virginia",
    'WI'=>"Wisconsin",
    'WY'=>"Wyoming",
    'AS'=>"American Samoa",
    'GU'=>'Guam',
    'MP'=>"Northern Mariana Islands",
    'PR'=>"Puerto Rico",
    'VI'=>"Virgin Islands",
    'FM'=>"Federated States of Micronesia",
    'MH'=>"Marshall Islands",
    'UM'=>"U.S. Minor Outlying Islands");
}
